# Generates living documentation from Gherkin feature files using the Pickles Docker image
# For more information see: https://github.com/prmiguel/pickles-report

name: Pickles Living Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  living-documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7
    - uses: docker://ghcr.io/prmiguel/pickles-report:latest
      with:
        args: >-
          --feature-directory=./src/test/resources/features
          --output-directory=./report
          -df=dhtml
    - name: Rename index.html file
      run: cp ./report/Index.html ./report/index.html
    - uses: actions/upload-artifact@v4
      with:
        name: pickles
        path: report/
    - name: Publish to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.6.9
      with:
        branch: pickles-pages
        folder: report/
